# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.srcs/sources_1/bd/hog_wrapper/ip/hog_wrapper_auto_ds_1/hog_wrapper_auto_ds_1.xci
# IP: The module: 'hog_wrapper_auto_ds_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_auto_ds_1/hog_wrapper_auto_ds_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hog_wrapper_auto_ds_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_auto_ds_1/hog_wrapper_auto_ds_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hog_wrapper_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.srcs/sources_1/bd/hog_wrapper/ip/hog_wrapper_auto_ds_1/hog_wrapper_auto_ds_1.xci
# IP: The module: 'hog_wrapper_auto_ds_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_auto_ds_1/hog_wrapper_auto_ds_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hog_wrapper_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_auto_ds_1/hog_wrapper_auto_ds_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hog_wrapper_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
