# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hog_wrapper/hog_wrapper.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hog_wrapper || ORIG_REF_NAME==hog_wrapper} -quiet] -quiet

# IP: bd/hog_wrapper/ip/hog_wrapper_hog_ip_axi_Nathan_0_0/hog_wrapper_hog_ip_axi_Nathan_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hog_wrapper_hog_ip_axi_Nathan_0_0 || ORIG_REF_NAME==hog_wrapper_hog_ip_axi_Nathan_0_0} -quiet] -quiet

# IP: bd/hog_wrapper/ip/hog_wrapper_zynq_ultra_ps_e_0_0/hog_wrapper_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hog_wrapper_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==hog_wrapper_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/hog_wrapper/ip/hog_wrapper_axi_dma_0_0/hog_wrapper_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hog_wrapper_axi_dma_0_0 || ORIG_REF_NAME==hog_wrapper_axi_dma_0_0} -quiet] -quiet

# IP: bd/hog_wrapper/ip/hog_wrapper_xbar_0/hog_wrapper_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hog_wrapper_xbar_0 || ORIG_REF_NAME==hog_wrapper_xbar_0} -quiet] -quiet

# IP: bd/hog_wrapper/ip/hog_wrapper_auto_ds_0/hog_wrapper_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hog_wrapper_auto_ds_0 || ORIG_REF_NAME==hog_wrapper_auto_ds_0} -quiet] -quiet

# IP: bd/hog_wrapper/ip/hog_wrapper_auto_pc_0/hog_wrapper_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hog_wrapper_auto_pc_0 || ORIG_REF_NAME==hog_wrapper_auto_pc_0} -quiet] -quiet

# IP: bd/hog_wrapper/ip/hog_wrapper_auto_ds_1/hog_wrapper_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hog_wrapper_auto_ds_1 || ORIG_REF_NAME==hog_wrapper_auto_ds_1} -quiet] -quiet

# IP: bd/hog_wrapper/ip/hog_wrapper_auto_pc_1/hog_wrapper_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hog_wrapper_auto_pc_1 || ORIG_REF_NAME==hog_wrapper_auto_pc_1} -quiet] -quiet

# IP: bd/hog_wrapper/ip/hog_wrapper_ps8_0_axi_periph_0/hog_wrapper_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hog_wrapper_ps8_0_axi_periph_0 || ORIG_REF_NAME==hog_wrapper_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/hog_wrapper/ip/hog_wrapper_rst_ps8_0_99M_0/hog_wrapper_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hog_wrapper_rst_ps8_0_99M_0 || ORIG_REF_NAME==hog_wrapper_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/hog_wrapper_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hog_wrapper_axi_smc_0 || ORIG_REF_NAME==hog_wrapper_axi_smc_0} -quiet] -quiet

# XDC: d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/hog_wrapper_ooc.xdc
