# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.runs/synth_1/hog_wrapper_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xck26-sfvc784-2LV-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.cache/wt [current_project]
set_property parent.project_path D:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:kv260_som:part0:1.4 [current_project]
set_property board_connections {som240_1_connector xilinx.com:kv260_carrier:som240_1_connector:1.3} [current_project]
set_property ip_repo_paths d:/tcc/nathanzeidan/nathanszeidan_tcc/hog/hog.srcs/sources_1/new [current_project]
update_ip_catalog
set_property ip_output_repo d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  D:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.srcs/sources_1/new/hogpack.vhd
  D:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.srcs/sources_1/new/win_cross_taps.vhd
  D:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.srcs/sources_1/new/grad_mag_bin.vhd
  D:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.srcs/sources_1/new/block_binarize_v3.vhd
  D:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.srcs/sources_1/new/hog_block_assemble.vhd
  D:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.srcs/sources_1/new/hog_cell_histogram.vhd
  D:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.srcs/sources_1/new/axis_block_serializer.vhd
  D:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.srcs/sources_1/new/hog_pipeline_link.vhd
  D:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.srcs/sources_1/new/hog_ip_axi_Nathan.vhd
  d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/hdl/hog_wrapper_wrapper.vhd
}
add_files D:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.srcs/sources_1/bd/hog_wrapper/hog_wrapper.bd
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_zynq_ultra_ps_e_0_0/hog_wrapper_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_zynq_ultra_ps_e_0_0/hog_wrapper_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_dma_0_0/hog_wrapper_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_dma_0_0/hog_wrapper_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_dma_0_0/hog_wrapper_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_xbar_0/hog_wrapper_xbar_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_auto_ds_0/hog_wrapper_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_auto_ds_0/hog_wrapper_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_auto_ds_0/hog_wrapper_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_auto_pc_0/hog_wrapper_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_auto_ds_1/hog_wrapper_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_auto_ds_1/hog_wrapper_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_auto_ds_1/hog_wrapper_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_auto_pc_1/hog_wrapper_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_rst_ps8_0_99M_0/hog_wrapper_rst_ps8_0_99M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_rst_ps8_0_99M_0/hog_wrapper_rst_ps8_0_99M_0.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_rst_ps8_0_99M_0/hog_wrapper_rst_ps8_0_99M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_1/bd_a5f0_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_1/bd_a5f0_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_2/bd_a5f0_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_3/bd_a5f0_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_4/bd_a5f0_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_5/bd_a5f0_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_6/bd_a5f0_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_10/bd_a5f0_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_11/bd_a5f0_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_12/bd_a5f0_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_16/bd_a5f0_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_17/bd_a5f0_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_18/bd_a5f0_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_19/bd_a5f0_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_20/bd_a5f0_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_21/bd_a5f0_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_22/bd_a5f0_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_23/bd_a5f0_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_24/bd_a5f0_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_25/bd_a5f0_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_27/bd_a5f0_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_28/bd_a5f0_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_29/bd_a5f0_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_30/bd_a5f0_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_31/bd_a5f0_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/bd_0/ip/ip_32/bd_a5f0_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/ip/hog_wrapper_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TCC/NathanZeidan/NathanSZeidan_TCC/HOG/HOG.gen/sources_1/bd/hog_wrapper/hog_wrapper_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top hog_wrapper_wrapper -part xck26-sfvc784-2LV-c
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef hog_wrapper_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file hog_wrapper_wrapper_utilization_synth.rpt -pb hog_wrapper_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
